// Layouts
export { default as AppLayout } from '@/layouts/AppLayout.vue';
export { default as AppSidebarLayout } from '@/layouts/app/AppSidebarLayout.vue';
export { default as AppHeaderLayout } from '@/layouts/app/AppHeaderLayout.vue';
export { default as AuthLayout } from '@/layouts/AuthLayout.vue';
export { default as AuthCardLayout } from '@/layouts/auth/AuthCardLayout.vue';
export { default as AuthSimpleLayout } from '@/layouts/auth/AuthSimpleLayout.vue';
export { default as AuthSplitLayout } from '@/layouts/auth/AuthSplitLayout.vue';
export { default as GuestLayout } from '@/layouts/GuestLayout.vue';
export { default as GuestSimpleLayout } from '@/layouts/guest/GuestSimpleLayout.vue';
export { default as StaticPageLayout } from '@/layouts/static/StaticPageLayout.vue';
export { default as CompanyLayout } from '@/layouts/company/Layout.vue';
export { default as SettingsLayout } from '@/layouts/settings/Layout.vue';

// Application shell components
export { default as AppShell } from '@/components/AppShell.vue';
export { default as AppHeader } from '@/components/AppHeader.vue';
export { default as AppSidebar } from '@/components/AppSidebar.vue';
export { default as AppSidebarHeader } from '@/components/AppSidebarHeader.vue';
export { default as AppContent } from '@/components/AppContent.vue';
export { default as AppLogo } from '@/components/AppLogo.vue';
export { default as AppLogoIcon } from '@/components/AppLogoIcon.vue';
export { default as NavMain } from '@/components/NavMain.vue';
export { default as NavFooter } from '@/components/NavFooter.vue';
export { default as NavUser } from '@/components/NavUser.vue';
export { default as TopNavbar } from '@/components/TopNavbar.vue';
export { default as Breadcrumbs } from '@/components/Breadcrumbs.vue';
export { default as UserMenuContent } from '@/components/UserMenuContent.vue';
export { default as UserInfo } from '@/components/UserInfo.vue';
export { default as AppearanceTabs } from '@/components/AppearanceTabs.vue';
export { default as Heading } from '@/components/Heading.vue';
export { default as HeadingSmall } from '@/components/HeadingSmall.vue';
export { default as TextLink } from '@/components/TextLink.vue';
export { default as Icon } from '@/components/Icon.vue';
export { default as InputError } from '@/components/InputError.vue';
export { default as PlaceholderPattern } from '@/components/PlaceholderPattern.vue';

// UI kit (prefix with Ui for clarity)
export { default as UiButton } from '@/components/ui/button/Button.vue';
export { default as UiInput } from '@/components/ui/input/Input.vue';
export { default as UiLabel } from '@/components/ui/label/Label.vue';
export { default as UiCheckbox } from '@/components/ui/checkbox/Checkbox.vue';
export { default as UiSelect } from '@/components/ui/select/Select.vue';
export { default as UiAvatar } from '@/components/ui/avatar/Avatar.vue';
export { default as UiAvatarImage } from '@/components/ui/avatar/AvatarImage.vue';
export { default as UiAvatarFallback } from '@/components/ui/avatar/AvatarFallback.vue';
export { default as UiCard } from '@/components/ui/card/Card.vue';
export { default as UiCardHeader } from '@/components/ui/card/CardHeader.vue';
export { default as UiCardTitle } from '@/components/ui/card/CardTitle.vue';
export { default as UiCardDescription } from '@/components/ui/card/CardDescription.vue';
export { default as UiCardContent } from '@/components/ui/card/CardContent.vue';
export { default as UiCardFooter } from '@/components/ui/card/CardFooter.vue';
export { default as UiDialog } from '@/components/ui/dialog/Dialog.vue';
export { default as UiDialogTrigger } from '@/components/ui/dialog/DialogTrigger.vue';
export { default as UiDialogOverlay } from '@/components/ui/dialog/DialogOverlay.vue';
export { default as UiDialogContent } from '@/components/ui/dialog/DialogContent.vue';
export { default as UiDialogHeader } from '@/components/ui/dialog/DialogHeader.vue';
export { default as UiDialogFooter } from '@/components/ui/dialog/DialogFooter.vue';
export { default as UiDialogTitle } from '@/components/ui/dialog/DialogTitle.vue';
export { default as UiDialogDescription } from '@/components/ui/dialog/DialogDescription.vue';
export { default as UiDialogClose } from '@/components/ui/dialog/DialogClose.vue';
export { default as UiDialogScrollContent } from '@/components/ui/dialog/DialogScrollContent.vue';
export { default as UiDropdownMenu } from '@/components/ui/dropdown-menu/DropdownMenu.vue';
export { default as UiDropdownMenuTrigger } from '@/components/ui/dropdown-menu/DropdownMenuTrigger.vue';
export { default as UiDropdownMenuContent } from '@/components/ui/dropdown-menu/DropdownMenuContent.vue';
export { default as UiDropdownMenuLabel } from '@/components/ui/dropdown-menu/DropdownMenuLabel.vue';
export { default as UiDropdownMenuItem } from '@/components/ui/dropdown-menu/DropdownMenuItem.vue';
export { default as UiDropdownMenuSeparator } from '@/components/ui/dropdown-menu/DropdownMenuSeparator.vue';
export { default as UiDropdownMenuGroup } from '@/components/ui/dropdown-menu/DropdownMenuGroup.vue';
export { default as UiDropdownMenuShortcut } from '@/components/ui/dropdown-menu/DropdownMenuShortcut.vue';
export { default as UiDropdownMenuCheckboxItem } from '@/components/ui/dropdown-menu/DropdownMenuCheckboxItem.vue';
export { default as UiDropdownMenuRadioGroup } from '@/components/ui/dropdown-menu/DropdownMenuRadioGroup.vue';
export { default as UiDropdownMenuRadioItem } from '@/components/ui/dropdown-menu/DropdownMenuRadioItem.vue';
export { default as UiDropdownMenuSub } from '@/components/ui/dropdown-menu/DropdownMenuSub.vue';
export { default as UiDropdownMenuSubTrigger } from '@/components/ui/dropdown-menu/DropdownMenuSubTrigger.vue';
export { default as UiDropdownMenuSubContent } from '@/components/ui/dropdown-menu/DropdownMenuSubContent.vue';
export { default as UiTooltip } from '@/components/ui/tooltip/Tooltip.vue';
export { default as UiTooltipProvider } from '@/components/ui/tooltip/TooltipProvider.vue';
export { default as UiTooltipTrigger } from '@/components/ui/tooltip/TooltipTrigger.vue';
export { default as UiTooltipContent } from '@/components/ui/tooltip/TooltipContent.vue';
export { default as UiSheet } from '@/components/ui/sheet/Sheet.vue';
export { default as UiSheetTrigger } from '@/components/ui/sheet/SheetTrigger.vue';
export { default as UiSheetContent } from '@/components/ui/sheet/SheetContent.vue';
export { default as UiSheetHeader } from '@/components/ui/sheet/SheetHeader.vue';
export { default as UiSheetTitle } from '@/components/ui/sheet/SheetTitle.vue';
export { default as UiSheetDescription } from '@/components/ui/sheet/SheetDescription.vue';
export { default as UiSheetFooter } from '@/components/ui/sheet/SheetFooter.vue';
export { default as UiSheetClose } from '@/components/ui/sheet/SheetClose.vue';
export { default as UiSheetOverlay } from '@/components/ui/sheet/SheetOverlay.vue';
export { default as UiSkeleton } from '@/components/ui/skeleton/Skeleton.vue';
export { default as UiSeparator } from '@/components/ui/separator/Separator.vue';
export { default as UiCollapsible } from '@/components/ui/collapsible/Collapsible.vue';
export { default as UiCollapsibleTrigger } from '@/components/ui/collapsible/CollapsibleTrigger.vue';
export { default as UiCollapsibleContent } from '@/components/ui/collapsible/CollapsibleContent.vue';
export { default as UiNavigationMenu } from '@/components/ui/navigation-menu/NavigationMenu.vue';
export { default as UiNavigationMenuList } from '@/components/ui/navigation-menu/NavigationMenuList.vue';
export { default as UiNavigationMenuItem } from '@/components/ui/navigation-menu/NavigationMenuItem.vue';
export { default as UiNavigationMenuTrigger } from '@/components/ui/navigation-menu/NavigationMenuTrigger.vue';
export { default as UiNavigationMenuContent } from '@/components/ui/navigation-menu/NavigationMenuContent.vue';
export { default as UiNavigationMenuLink } from '@/components/ui/navigation-menu/NavigationMenuLink.vue';
export { default as UiNavigationMenuIndicator } from '@/components/ui/navigation-menu/NavigationMenuIndicator.vue';
export { default as UiNavigationMenuViewport } from '@/components/ui/navigation-menu/NavigationMenuViewport.vue';
export { default as UiBreadcrumb } from '@/components/ui/breadcrumb/Breadcrumb.vue';
export { default as UiBreadcrumbList } from '@/components/ui/breadcrumb/BreadcrumbList.vue';
export { default as UiBreadcrumbItem } from '@/components/ui/breadcrumb/BreadcrumbItem.vue';
export { default as UiBreadcrumbLink } from '@/components/ui/breadcrumb/BreadcrumbLink.vue';
export { default as UiBreadcrumbPage } from '@/components/ui/breadcrumb/BreadcrumbPage.vue';
export { default as UiBreadcrumbSeparator } from '@/components/ui/breadcrumb/BreadcrumbSeparator.vue';
export { default as UiBreadcrumbEllipsis } from '@/components/ui/breadcrumb/BreadcrumbEllipsis.vue';
export { default as UiSidebar } from '@/components/ui/sidebar/Sidebar.vue';
export { default as UiSidebarProvider } from '@/components/ui/sidebar/SidebarProvider.vue';
export { default as UiSidebarContent } from '@/components/ui/sidebar/SidebarContent.vue';
export { default as UiSidebarHeader } from '@/components/ui/sidebar/SidebarHeader.vue';
export { default as UiSidebarFooter } from '@/components/ui/sidebar/SidebarFooter.vue';
export { default as UiSidebarTrigger } from '@/components/ui/sidebar/SidebarTrigger.vue';
export { default as UiSidebarInset } from '@/components/ui/sidebar/SidebarInset.vue';
export { default as UiSidebarMenu } from '@/components/ui/sidebar/SidebarMenu.vue';
export { default as UiSidebarMenuItem } from '@/components/ui/sidebar/SidebarMenuItem.vue';
export { default as UiSidebarMenuButton } from '@/components/ui/sidebar/SidebarMenuButton.vue';
export { default as UiSidebarMenuButtonChild } from '@/components/ui/sidebar/SidebarMenuButtonChild.vue';
export { default as UiSidebarMenuSub } from '@/components/ui/sidebar/SidebarMenuSub.vue';
export { default as UiSidebarMenuSubItem } from '@/components/ui/sidebar/SidebarMenuSubItem.vue';
export { default as UiSidebarMenuSubButton } from '@/components/ui/sidebar/SidebarMenuSubButton.vue';
export { default as UiSidebarMenuBadge } from '@/components/ui/sidebar/SidebarMenuBadge.vue';
export { default as UiSidebarMenuAction } from '@/components/ui/sidebar/SidebarMenuAction.vue';
export { default as UiSidebarMenuSkeleton } from '@/components/ui/sidebar/SidebarMenuSkeleton.vue';
export { default as UiSidebarInput } from '@/components/ui/sidebar/SidebarInput.vue';
export { default as UiSidebarGroup } from '@/components/ui/sidebar/SidebarGroup.vue';
export { default as UiSidebarGroupLabel } from '@/components/ui/sidebar/SidebarGroupLabel.vue';
export { default as UiSidebarGroupContent } from '@/components/ui/sidebar/SidebarGroupContent.vue';
export { default as UiSidebarGroupAction } from '@/components/ui/sidebar/SidebarGroupAction.vue';
export { default as UiSidebarSeparator } from '@/components/ui/sidebar/SidebarSeparator.vue';
export { default as UiSidebarRail } from '@/components/ui/sidebar/SidebarRail.vue';

// Utilities & data
export { cn, formatTitle } from '@/lib/utils';
export { resolveIcon } from '@/lib/icons';
export type { CountryRecord, CountryRegion, CountryCode } from '@/lib/countries';
export { AMERICAS_COUNTRIES } from '@/lib/countries';

// Composables
export { initializeTheme, updateTheme, useAppearance } from '@/composables/useAppearance';
export { getInitials, useInitials } from '@/composables/useInitials';
export { useRecaptcha } from '@/composables/useRecaptcha';
export type { RecaptchaConfig } from '@/composables/useRecaptcha';

// Global helpers
export { trans } from 'laravel-vue-i18n';
export { route, useRoute } from 'ziggy-js';
